### ISSUE TITLE
Code of Conduct Draft

### ISSUE THREAD

**Issue by ibrand** [ProgressiveHackNight/admin#1]
This requires an online and offline CoC.

- The offline version will be based off of the Recurse Center's
- The online version will include that ^ but be more extensive

**Comment by laveshaparker** [comment]
The doc lives [here](https://docs.google.com/document/d/1r8qxWtwnUof3AfkvFfRZrsWP1F65BHThp39cp3oyRlY/edit#heading=h.rmalkndryvxs)!

**Comment by laveshaparker** [comment]
Can this be moved to "Done" @ibrand? :)

**Comment by ibrand** [comment]
Yep! Moving now :D
