### ISSUE TITLE
Fork ChiHackNight Jekyll Site

### ISSUE THREAD

**Issue by ibrand** [ProgressiveHackNight/admin#2]
- [ ] Find the ChiHackNight main site repo
- [ ] Fork the repo
- [ ] Replace the logo and put our branding on it
- [ ] Deploy to github pages

**Comment by julianrad** [comment]
I do think that we need a central web site for all the things, but I'm not a huge fan of the ChiHackNight UX.

**Comment by laveshaparker** [comment]
@julianrad is this a dislike of the entire setup of ChiHackNight's site, or is it more cosmetic? Building our own site from scratch will take a *long* time, but forking this is pretty convenient if we can just make aesthetic updates.

**Comment by julianrad** [comment]
@vesha I feel like the chihacknight site is very insular - if you know about chihacknight, then it's easy for you to navigate the site. If you don't know chihacknight, I'm not getting a really clear idea of what is going on.

I don't think we need create some massive huge site - I actually think that if we keep it super simple and be super aggressive in keeping up social pages and outward facing common sites (like Github) the landing page is really more about 01 welcoming new and prospective attendees and giving them a way to RSVP/etc 02 a clear delineation of the rules and what to expect at a PHN 03 a default aggregate of everywhere to find everything from YouTube videos to blog posts to speaker twitter handles to social pages and posts 04 how to get more information. On the deeper end we should definitely discuss our hopes and dreams for project vetting and attendee information (to better hook up workgroups with volunteers). But I think we're better served thinking through this stuff before we just fork off what works for them.

**Comment by laveshaparker** [comment]
Totally fair--we can discuss this at the next meeting. I'll add it to the agenda. I'm assuming we should work through @tktino's user journey doc at this point, as that will likely be noted as a blocker when we discuss this site next week. I'll pull that issue out of the backlog so it's on our radar.

**Comment by laveshaparker** [comment]
Going to close this out, as @rapicastillo forked the site already. It lives [here](http://www.proghacknight.org.s3-website-us-east-1.amazonaws.com/). I want to continue the conversation that was going on here, so let's come up with new tickets for the site in the next steering committee meeting. Thanks!
