### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by ibrand** [ProgressiveHackNight/admin#3]
_tbd_

**Comment by julianrad** [comment]
I think considering that we're sticking with Progressive HackNight, we should also stick with the current logo.

But - I do have a couple of questions about our name and it's representation - are we:

Progressive HackNight
Progressive Hack Night
Prog HackNight
ProgHackNight
Prog Hack Night

For me - I think right now as we're establishing ourselves, we should choose one and stick with it in all references - Progressive HackNight. But this has ramifications across all of our outward facing pages from Twitter to YouTube to our webpage.

What are your thoughts?

**Comment by ibrand** [comment]
I agree. I think Progressive HackNight is the name we've been codifying in our docs and such and is a name that is fully expressive and clear.

**Comment by laveshaparker** [comment]
I third "Progressive HackNight"

I know nothing about designing logos, but I would like to see if our logo could be more descriptive of what this event is. It's also pretty reminiscent of ProgCode's logo, which I don't think is the best thing for us as we're a separate entity.

**Comment by julianrad** [comment]
To my eye, the logo has enough distance from PC, but I hear your desire to make something that is more visually descriptive of a PHN. Did you have any thoughts or reference or scrap of what you're envisioning?

**Comment by laveshaparker** [comment]
> Did you have any thoughts or reference or scrap of what you're envisioning?

I honestly don't. I'll keep an eye out for any symbols that might invoke thoughts of what we're working to do, but I will honestly be about 0 help with creating anything visual (my design eye lies in other places), I can only provide comments on existing designs.

**Comment by julianrad** [comment]
OK got it. Anyone else with a vision or thoughts about what might be a good direction toward which creative work can be accomplished? Can we hear from the group on everyone's feelings about the logo?

**Comment by ibrand** [comment]
One thing that @tktino mentioned that I thought was interesting was that it's a tricky logo because it doesn't translate to being just monotone. I happen to really like the logo, but I see what he means about it being tricky as a mark since we can't convert it smoothly to black-and-white and still have it's full impact

**Comment by julianrad** [comment]
@tktino is right that the current version of the logo doesn't translate intuitively to monotone or knock out, but I think we can certainly make grayscale and black and white variants that would work.

What's more important is whether or not it's something we want to explore. Admittedly I'm a little gunshy after the logo redesign merry-go-round that happened at Prog Code, so I'm asking for consensus on this subject before we start down that path.

My two cents - I think the current logo works. It shares a visual DNA with Prog Code and ChiHackNight, and while we're brand building that's not a bad thing. Honestly as long as we keep the name "Progressive" and have Prog Code people in the steering committee, we're always going to have a strong association with Prog Code which is again, not a bad thing. The use of the star inside the circle being reminiscent of a compass and map way finding rosette is a great visual representation of what we are looking for Progressive HackNight to become for projects and activism. I'd vote for keeping our name and our logo as is - for now, let's concentrate on our other brand building assets (like fonts and colors and social) and values (like the CoC and User Journey and protocols).

**Comment by ibrand** [comment]
I totally agree with that ^ :) well said @julianrad. I totally think fonts and process are a better thing to focus on first.
