### ISSUE TITLE
Ping Julian About a Naming Doc

### ISSUE THREAD

**Issue by ibrand** [ProgressiveHackNight/admin#4]
Ensure that we have a shared doc of names for everyone to contribute to and a deadline for voting on a name in the doc.

**Comment by laveshaparker** [comment]
The doc lives [here](https://docs.google.com/spreadsheets/d/1WWWb7hFqnbmui8xlCRQ13DgjxhemuaH3vquinxUs4QY/edit?usp=sharing). Deadline to add suggestions is Friday, May 26, and deadline to vote is Sunday, May 28.
