### ISSUE TITLE
Contact existing projects about our impact thus far

### ISSUE THREAD

**Issue by laveshaparker** [ProgressiveHackNight/admin#9]
Ask existing projects what Progressive Hacknight has accomplished for them, and how we can improve/continue to support them.

**Comment by laveshaparker** [comment]
Hi @rapicastillo @rcscastillo (idk which of these usernames you use most frequently)! Do you know if you'll have time to do this soon? If not, I can email these groups if I can find their contact info!

**Comment by rapicastillo** [comment]
Will be able to do it starting next week! but they should all be in

https://github.com/ProgressiveHackNight/breakout-groups/issues 

Their contact info should be in there as well.

**Comment by laveshaparker** [comment]
Cool! Then I'll leave this assigned to you :)
